# Generated by Django 3.0.6 on 2020-05-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='produits',
            field=models.ManyToManyField(through='backoffice.Achat', to='backoffice.Produit'),
        ),
    ]
